name: data_storeholder
description: Simple package that allows you to store, retrieve and listen to your data anywhere across in your project.
homepage: https://github.com/kulishnik22/Store
version: 1.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
